//all users password is '12345678'
export const Users = [
	{
		id: 1,
		profilePicture: "person/z1.jpg",
		username: "Zen Wong",
	},
	{
		id: 2,
		profilePicture: "person/z2.jpg",
		username: "Jie Jimmie",
	},
	{
		id: 3,
		profilePicture: "person/z3.jpg",
		username: "Jamey Oakley",
	},
	{
		id: 4,
		profilePicture: "person/z4.jpg",
		username: "Royal Arden",
	},
	{
		id: 5,
		profilePicture: "person/z5.jpg",
		username: "Yahui Jun",
	},
	{
		id: 6,
		profilePicture: "person/z6.jpg",
		username: "Whitney Kendal",
	},
	{
		id: 7,
		profilePicture: "person/z7.jpg",
		username: "Wu Chang",
	},
	{
		id: 8,
		profilePicture: "person/z8.jpg",
		username: "Christie Camryn",
	},
	{
		id: 9,
		profilePicture: "person/z9.jpg",
		username: "Hilary Dale",
	},
	{
		id: 10,
		profilePicture: "person/z10.jpg",
		username: "Yannick Darian",
	},
];

export const Posts = [
	{
		id: 1,
		desc: "I don't know how or when but I know that it will.",
		photo: "post/z1.jpg",
		date: "5 mins ago",
		userId: 1,
		like: 32,
		comment: 9,
	},
	{
		id: 2,
		photo: "post/z2.jpg",
		date: "15 mins ago",
		userId: 2,
		like: 2,
		comment: 1,
	},
	{
		id: 3,
		desc: "Every moment is a fresh beginning.",
		photo: "post/z3.jpg",
		date: "1 hour ago",
		userId: 3,
		like: 61,
		comment: 2,
	},
	{
		id: 4,
		photo: "post/z4.jpg",
		date: "4 hours ago",
		userId: 4,
		like: 7,
		comment: 3,
	},
	{
		id: 5,
		photo: "post/z5.jpg",
		date: "5 hours ago",
		userId: 5,
		like: 23,
		comment: 5,
	},
	{
		id: 6,
		photo: "post/z6.jpg",
		date: "1 day ago",
		userId: 6,
		like: 44,
		comment: 6,
	},
	{
		id: 7,
		desc: "Never regret anything that made you smile.",
		photo: "post/z7.jpg",
		date: "2 days ago",
		userId: 7,
		like: 52,
		comment: 3,
	},
	{
		id: 8,
		photo: "post/z8.jpg",
		date: "3 days ago",
		userId: 8,
		like: 15,
		comment: 1,
	},
	{
		id: 9,
		desc: "Change the world by being yourself.",
		photo: "post/z9.jpg",
		date: "5 days ago",
		userId: 9,
		like: 11,
		comment: 2,
	},
	{
		id: 10,
		photo: "post/z10.jpg",
		date: "1 week ago",
		userId: 10,
		like: 104,
		comment: 12,
	},
];
